version: '3'

services:
  reporte:
    build: ./microsrv-reporte
    depends_on:
      - mongo
    environment:
      - DB_MONGO=mongodb://mongo:27017/Microsv_reporte
  monolitico:
    build: ./monolitico
    depends_on:
      - mongo
    environment:
      - DB_MONGO=mongodb://mongo:27017/Monolitico
  mongo:
    image: mongo
    ports:
      - '27018:27017'
    command: mongod --quiet --logpath /dev/null
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - reporte
      - monolitico